# Generated by Django 1.10.6 on 2017-05-03 14:38
import os
import csv
from django.db import migrations
from django.conf import settings
from procapi.processo.models import (
    TipoDocumento,
    Assunto,
    OrgaoJulgador,
    Localidade,
    Classe
)

MAPA_DADOS_INICIAIS = [
    (Assunto, 'init_assuntos.csv', {"codigo": 0, "nome": 1}),
    (OrgaoJulgador, 'init_orgaos_julgadores.csv', {"codigo": 0, "nome": 1}),
    (Localidade, 'init_localidades.csv', {"codigo": 0, "nome": 1}),
    (Classe, 'init_classes.csv', {"codigo": 0, "nome": 1}),
    (TipoDocumento, 'init_tipos_documento.csv', {"codigo": 0, "nome": 1, "grau": 2}),
]


def popular_db(mongo_model_class: object, filename: str, fields_dict: dict):
    filename = os.path.join(settings.CSV_INITIAL_DATA_PATH, filename)
    with open(filename, 'r') as csvfile:
        spamreader = csv.reader(csvfile, delimiter=str(';'), quotechar=str('"'))
        for row in spamreader:
            if not mongo_model_class.objects.filter(codigo=row[0]).count():
                d = {}
                for chave, indice in list(fields_dict.items()):
                    d[chave] = row[indice]
                mongo_model_class.objects.create(**d)


def remover_dados(mongo_model_class: object, filename: str, fields_dict: dict):
    filename = os.path.join(settings.CSV_INITIAL_DATA_PATH, filename)
    with open(filename, 'r') as csvfile:
        spamreader = csv.reader(csvfile, delimiter=str(';'), quotechar=str('"'))
        codigos = [row[0] for row in spamreader]
        mongo_model_class.objects.filter(codigo__in=codigos).delete()


def criar_dados_iniciais_mongodb(apps, schema_editor):
    for d in MAPA_DADOS_INICIAIS:
        popular_db(d[0], d[1], d[2])


def excluir_dados_iniciais_mongodb(apps, schema_editor):
    for d in MAPA_DADOS_INICIAIS:
        remover_dados(d[0], d[1], d[2])


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(code=criar_dados_iniciais_mongodb, reverse_code=excluir_dados_iniciais_mongodb),
    ]
